FROM dockerfile_pg:1
RUN apt-get update &&\
  apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev git curl wget libpq-dev vim tcl redis-server
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(rbenv init -)"' >> ~/.bashrc
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
RUN $HOME/.rbenv/bin/rbenv install 2.3.0
RUN $HOME/.rbenv/bin/rbenv global 2.3.0
RUN $HOME/.rbenv/bin/rbenv install 2.5.0
RUN $HOME/.rbenv/versions/2.3.0/bin/gem install bundler -v 1.17.3
RUN $HOME/.rbenv/versions/2.5.0/bin/gem install rails -v 4.2.4
WORKDIR /root
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# Instaling nodejs for both rails & angular
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get install --yes nodejs
RUN npm install -g bower@1.8.8
RUN npm install -g gulp@2.2.0

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 3003
EXPOSE 3004
EXPOSE 3005
EXPOSE 9000
CMD [ "./entrypoint.sh" ]

